spring:
  profiles:
    active: "dev"
    include: db,security
---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: "ops"
---
server:
  port: 8081
spring:
  config:
    activate:
      on-profile: "dev"
